### ISSUE TITLE
OpenInvite should be in local time

### ISSUE THREAD

**Issue by mjwsteenbergen** [mjwsteenbergen/mjwsteenbergen.github.io#6]

**Comment by devbridie** [comment]
Beste Martijn JW Steenbergen.

Vandaag heb ik, trouwe ontvanger van de Agenda Uitnodigingen, stevig mij gearbeid ten behoeve van de Verbetering van de Dienst waarmee mijn Elektronische Agenda wordt gevuld. Graag wil ik Uw aandacht richten tot de resultaten van mijn nederige werk, moge het U blieven. Voor Uw gemak heb ik de Trek Verzoek in de komende tekens geplaatst, zodat U zich kunt bezighouden met Uw werk. #7

**Comment by mjwsteenbergen** [comment]
Closed by #7 
Veel dank aan @devbridie
